/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Unicode-Normalize.h
 #	source generated by 4D Plugin Wizard
 #	Project : Unicode Normalize
 #	author : miyako
 #	2024/02/26
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_UNICODE_NORMALIZE_H
#define PLUGIN_UNICODE_NORMALIZE_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"

#if VERSIONMAC
#import<Cocoa/Cocoa.h>
#else

#endif

typedef enum {
    normalization_form_nfc = 0,
    normalization_form_nfd = 1,
    normalization_form_nfkc = 2,
    normalization_form_nfkd = 3
} normalization_form_t;

#pragma mark -

static void Unicode_normalize(PA_PluginParameters params);

#endif /* PLUGIN_UNICODE_NORMALIZE_H */
